version: '3.1'

services:

    web: #Serviço do apache_php
        build: 
            context: ./php
            dockerfile: dockerfile #Arquivo de configuração do apache
        container_name: php_serve
        depends_on: #Força esse serviço a utilizar o serviço do banco (db)
            - db
        volumes: 
            - ./php:/var/www/html/
        ports: 
            - 80:80
        networks: 
            - frontend
    db: #Banco mysql
        container_name: mysql_serve
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment: 
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: test_db
            MYSQL_USER: roberto
            MYSQL_PASSWORD: roberto
        volumes:
            - ./volume-mysql:/var/lib/mysql
        ports: 
            - 6033:3306
        networks: 
            - frontend
    phpmyadmin: #Gerenciador do banco
        image: phpmyadmin/phpmyadmin # Imagem a ser utulizada
        depends_on: #Força esse serviço a utilizar o serviço do banco (db)
            - db
        environment:
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - ./uploads.ini:/usr/local/etc/php/conf.d/php-phpmyadmin.ini
        ports:
            - "8080:80"
        networks: 
            - frontend
networks: 
    - frontend
